In [3]:
import numpy as np

In [6]:
list = [10,20,30,40,50,60]
arr = np.array(list)

In [7]:
arr

array([10, 20, 30, 40, 50, 60])

In [14]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
arr2 = np.array(matrix)

In [15]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [19]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [25]:
print(arr)

[10 20 30 40 50 60]


In [27]:
print(arr[1:4])

[20 30 40]


In [30]:
print(arr2[0, 2]) 

3


In [32]:
l1 = [1,2,3,4]

In [35]:
l2 = [5,6,7,8]

In [36]:
np.stack((l1,l2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [38]:
np.vstack((l1,l2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [39]:
np.hstack((l1,l2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [41]:
import numpy as np

# 1. Start with one array of names
names = np.array(["John Doe", "Jane Smith"])
print("Original:", names)

# 2. SPLIT: Break each name into [First, Last]
# (We use Python's built-in split here just to separate the strings)
first_names = np.array(["John", "Jane"])
last_names = np.array(["Doe", "Smith"])

# 3. MODIFY: Change just the first names
added_title = np.array(["Mr. John", "Ms. Jane"])

# 4. STACK: Glue the modified first names back to the last names
final_list = np.hstack((added_title, last_names))
print("\nStacked back together:\n", final_list)


Original: ['John Doe' 'Jane Smith']

Stacked back together:
 ['Mr. John' 'Ms. Jane' 'Doe' 'Smith']
