In [1]:
#How do you create a NumPy array from the list [1, 2, 3, 4, 5]?

In [1]:
import numpy as np

In [2]:
list = [1,2,3,4,5]

In [3]:
list

[1, 2, 3, 4, 5]

In [4]:
numpyarrlist=np.array(list)

In [6]:
numpyarrlist

array([1, 2, 3, 4, 5])

In [7]:
#What is the output of np.array([10, 20, 30, 40])[2]?

In [8]:
np.array([10, 20, 30, 40])[2]

np.int64(30)

In [9]:
#Create a NumPy array containing integers from 1 to 10.

In [14]:
numpyarr=np.arange(1,11)
numpyarr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
#Create a NumPy array containing five zeros.
numpyarr = np.zeros(5,dtype=int)
numpyarr 


array([0, 0, 0, 0, 0])

In [23]:
#Create a 3 × 3 NumPy array containing only ones.
list=np.ones(9,dtype=int).reshape(3,3)
list

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [25]:
#What is the shape of np.array([[1, 2, 3], [4, 5, 6]])?
np.array([[1, 2, 3], [4, 5, 6]]).shape

(2, 3)

In [26]:
#What is the number of dimensions of np.array([[1, 2], [3, 4], [5, 6]])?
np.array([[1, 2], [3, 4], [5, 6]]).shape

(3, 2)

In [32]:
#Given arr = np.array([10, 20, 30, 40, 50]), extract the elements from index 1 to index 3.
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:3])

[20 30]


In [35]:
#Given arr = np.array([1, 2, 3, 4, 5]), multiply every element by 10.
arr = np.array([1, 2, 3, 4, 5])*10

print(arr)

[10 20 30 40 50]


In [43]:
#Find the sum, mean, maximum, and minimum of np.array([12, 5, 8, 20, 15]).
smmm=np.array([12, 5, 8, 20, 15])
print(smmm.sum())
print(smmm.mean())
print(smmm.min())
print(smmm.max())


60
12.0
5
20


In [50]:
#Given arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10]), extract only the even numbers.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(arr[arr%2==0])

[ 2  4  6  8 10]


In [55]:

#Sort np.array([5, 2, 8, 1, 9, 3]) in ascending order.
a=np.array([5, 2, 8, 1, 9, 3])
a.sort()
a

array([1, 2, 3, 5, 8, 9])

In [59]:
#Find the indices of elements greater than 50 in np.array([10, 60, 30, 80, 45, 90]).
b=np.array([10, 60, 30, 80, 45, 90])
indices=np.where(b>50)
print(indices)

(array([1, 3, 5]),)


In [61]:
#Reshape np.array([1, 2, 3, 4, 5, 6]) into a 2 × 3 array.
np.array([1, 2, 3, 4, 5, 6]).reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
#Given two arrays [1, 2, 3] and [4, 5, 6], perform element-wise addition, subtraction, multiplication, and division.
a=np.array([1, 2, 3])
b=np.array([4, 5, 6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [72]:
#Perform matrix multiplication on [[1, 2], [3, 4]] and [[5, 6], [7, 8]].
a=np.array([[1, 2], [3, 4]])
b=np.array([[5, 6], [7, 8]])
print(a@b)

[[19 22]
 [43 50]]


In [73]:
#Find the transpose of [[1, 2, 3], [4, 5, 6]].
a=np.array([[1, 2, 3], [4, 5, 6]])
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [75]:
#Replace all values greater than 3 with 100 in np.array([1, 2, 3, 4, 5]).
a=np.array([1, 2, 3, 4, 5])
a[a>3]=100
print(a)

[  1   2   3 100 100]


In [78]:
#Create a 5 × 5 array containing numbers from 1 to 25 and extract the second row and third column.
a=np.arange(1,26)
b=a.reshape(5,5)
print(b)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [85]:
print("Second Row:",b[1,:])
print("Third Column:",b[:,2])

Second Row: [ 6  7  8  9 10]
Third Column: [ 3  8 13 18 23]


In [95]:
#Given [[10, 20, 30], [40, 50, 60], [70, 80, 90]], find the row sums, column sums, overall mean, and elements greater than 45.
a=np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(a.sum(axis=1))
print(a.sum(axis=0))
print(a.mean())
print(a[a>45])

[ 60 150 240]
[120 150 180]
50.0
[50 60 70 80 90]


In [98]:
#Create a NumPy array containing all even numbers from 2 to 20.
a = np.arange(2,21,2)
print(a)

[ 2  4  6  8 10 12 14 16 18 20]


In [99]:
#Create a NumPy array containing 10 equally spaced values between 0 and 1.
a=np.linspace(0,1,10)
print(a)


[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [101]:
#Given arr = np.array([3, 7, 2, 9, 4, 8]), find the index of the maximum value.
arr = np.array([3, 7, 2, 9, 4, 8])
mindex = np.argmax(arr)
print(mindex)

3


In [103]:
#Given arr = np.array([10, 20, 30, 40, 50]), reverse the array.
arr = np.array([10, 20, 30, 40, 50])
reverse_arr= arr[::-1]
print(reverse_arr)

[50 40 30 20 10]


In [105]:
#Find the unique values in np.array([1, 2, 2, 3, 4, 4, 5]).
a=np.array([1, 2, 2, 3, 4, 4, 5])
b=np.unique(a)
b

array([1, 2, 3, 4, 5])

In [107]:
#Count how many elements are greater than 25 in np.array([10, 30, 15, 40, 25, 50]).
a = np.array([10, 30, 15, 40, 25, 50])
b = np.sum(a>25)
print(b)

3


In [109]:
#Convert the following 1D array into a 3 × 3 array: np.array([1,2,3,4,5,6,7,8,9]).
a = np.array([1,2,3,4,5,6,7,8,9])
b = a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [112]:
#Flatten the array [[1, 2], [3, 4], [5, 6]] into a 1D array.
a= np.array([[1, 2], [3, 4], [5, 6]])
b = a.flatten()
print(b)

[1 2 3 4 5 6]


In [115]:
#Concatenate np.array([1,2,3]) and np.array([4,5,6]).
a= np.array([1,2,3])
b= np.array([4,5,6])
c= np.concatenate((a,b))
print(c)

[1 2 3 4 5 6]


In [117]:
#Split np.array([1,2,3,4,5,6]) into three equal parts.
a= np.array([1,2,3,4,5,6])
b= np.split(a,3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]
